#!/usr/bin/env python3
"""House back-porch STAND-INS (2026-09-24): the forest bed, the window bursting, the guillotine,
the watermelon, the three forest ghosts and the witch.

    python3 tools/make_sfx_house_porch.py
    /Applications/Godot.app/Contents/MacOS/Godot --headless --path game --import

⚠️ These are PLACEHOLDERS. The user will supply real recordings; `docs/TODO_sounds.md`
("2026-09-24 — House porch pass (stand-ins)") carries the prompt for each. When a real file
arrives, delete that name from SOUNDS below (or drop the file over the .wav with the same base
name) — do NOT re-run this tool afterwards without doing so, or it silently overwrites the
real recording.

Pure stdlib, 44.1 kHz 16-bit mono, one seeded RNG PER SOUND (so adding a twelfth sound never
changes the other eleven — the make_sfx_backrooms.py lesson). Base names checked globally
unique on 2026-09-24 (`GameState.load_audio()` resolves by base name across every subdir).

Voices (the scream, the screech, the howl, the hum) are ADDITIVE: each harmonic of a moving
f0 is weighted by a formant envelope evaluated at that harmonic's frequency, which is a
source-filter voice without a filter's stability problems. Harshness is tanh.

`window_burst` layers the shared `glass_break.wav` under a synthesised shard tail when that
file exists (it is not generated by any tool here, so re-running is still deterministic).

Level targets (peak dBFS): stings -3, 3D one-shots -4..-6, the loop bed -12, the hum -10.
Every file prints its peak, RMS and loudest-300 ms, which is what a caller's volume_db should
be set from — never from a plausible number.
"""

import math
import os
import random
import struct
import wave

SR = 44100
ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
OUT_DIR = os.path.join(ROOT, "game", "assets", "audio", "level_2_house")
GLASS = os.path.join(ROOT, "game", "assets", "audio", "shared", "glass_break.wav")
TAU = 2.0 * math.pi


# ----------------------------------------------------------------------------- primitives
def buf(seconds):
    return [0.0] * int(SR * seconds)


def env_ad(t, a, d):
    return (t / a) if t < a else math.exp(-(t - a) / d)


def add(out, start, fn, length):
    s0 = int(start * SR)
    for i in range(int(length * SR)):
        j = s0 + i
        if 0 <= j < len(out):
            out[j] += fn(i / SR)


def lowpass(x, fc):
    a = 1.0 - math.exp(-TAU * fc / SR)
    y, out = 0.0, []
    for v in x:
        y += a * (v - y)
        out.append(y)
    return out


def highpass(x, fc):
    lp = lowpass(x, fc)
    return [a - b for a, b in zip(x, lp)]


class BandPass:
    """RBJ band-pass (0 dB peak), coefficients settable per block."""

    def __init__(self):
        self.x1 = self.x2 = self.y1 = self.y2 = 0.0
        self.set(1000.0, 1.0)

    def set(self, fc, q):
        fc = max(20.0, min(fc, SR * 0.45))
        w = TAU * fc / SR
        alpha = math.sin(w) / (2 * q)
        a0 = 1 + alpha
        self.b0, self.b2 = alpha / a0, -alpha / a0
        self.a1, self.a2 = -2 * math.cos(w) / a0, (1 - alpha) / a0

    def __call__(self, x):
        y = self.b0 * x + self.b2 * self.x2 - self.a1 * self.y1 - self.a2 * self.y2
        self.x2, self.x1 = self.x1, x
        self.y2, self.y1 = self.y1, y
        return y


def sweep_bp(x, fc_of_t, q):
    bp = BandPass()
    out = []
    for i, v in enumerate(x):
        if i % 32 == 0:
            bp.set(fc_of_t(i / SR), q)
        out.append(bp(v))
    return out


def formant_gain(f, formants):
    """Sum of resonance bumps: formants = [(centre Hz, bandwidth Hz, gain)]."""
    g = 0.0
    for fc, bw, amp in formants:
        d = (f - fc) / (bw * 0.5)
        g += amp / (1.0 + d * d)
    return g


def voice(seconds, f0_of_t, formants_of_t, amp_of_t, max_hz=9000.0, jitter=0.0, rng=None,
          block=64):
    """Additive source-filter voice. f0/formants/amp are functions of time."""
    n = int(SR * seconds)
    out = [0.0] * n
    phase = 0.0
    weights = []
    jit = 0.0
    for i in range(n):
        t = i / SR
        if i % block == 0:
            f0 = f0_of_t(t)
            if rng is not None and jitter:
                jit = jit * 0.7 + rng.uniform(-1, 1) * jitter * 0.3
            f0 *= 1.0 + jit
            forms = formants_of_t(t)
            k_max = max(1, int(max_hz / max(f0, 1.0)))
            weights = [formant_gain(k * f0, forms) / math.sqrt(k) for k in range(1, k_max + 1)]
            step = TAU * f0 / SR
        phase += step
        s = 0.0
        for k, w in enumerate(weights, 1):
            s += w * math.sin(k * phase)
        out[i] = s * amp_of_t(t)
    return out


def comb_reverb(x, mix, decay_s, tail_s=0.0):
    """Tiny Schroeder: four combs + two all-passes. `tail_s` extends the buffer."""
    x = x + [0.0] * int(SR * tail_s)
    delays = [1557, 1617, 1491, 1422]
    wet = [0.0] * len(x)
    for d in delays:
        g = 10 ** (-3.0 * d / SR / decay_s)
        line = [0.0] * d
        idx = 0
        for i, v in enumerate(x):
            y = line[idx]
            line[idx] = v + y * g
            idx = (idx + 1) % d
            wet[i] += y * 0.25
    for d, g in ((225, 0.5), (556, 0.5)):
        line = [0.0] * d
        idx = 0
        for i, v in enumerate(wet):
            b = line[idx]
            y = -g * v + b
            line[idx] = v + g * y
            idx = (idx + 1) % d
            wet[i] = y
    return [a * (1 - mix) + b * mix for a, b in zip(x, wet)]


def saturate(x, drive):
    return [math.tanh(v * drive) for v in x]


def fade(x, fin, fout):
    n = len(x)
    a, b = int(fin * SR), int(fout * SR)
    for i in range(a):
        x[i] *= i / a
    for i in range(b):
        x[n - 1 - i] *= i / b
    return x


def measure(x):
    peak = max(abs(v) for v in x) or 1e-9
    rms = math.sqrt(sum(v * v for v in x) / len(x)) or 1e-9
    w = int(0.3 * SR)
    best = 0.0
    step = w // 4
    for s in range(0, max(1, len(x) - w), step):
        seg = x[s:s + w]
        best = max(best, sum(v * v for v in seg) / len(seg))
    return 20 * math.log10(peak), 20 * math.log10(rms), 10 * math.log10(best or 1e-18)


def write(name, x, peak_db):
    peak = max(abs(v) for v in x) or 1e-9
    g = 10 ** (peak_db / 20.0) / peak
    y = [max(-1.0, min(1.0, v * g)) for v in x]
    path = os.path.join(OUT_DIR, name)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(b"".join(struct.pack("<h", int(v * 32767)) for v in y))
    p, r, l3 = measure(y)
    print("%-26s %5.2fs  peak %6.1f  RMS %6.1f  loudest-300ms %6.1f dBFS" % (name, len(y) / SR, p, r, l3))


def read_wav(path):
    with wave.open(path, "rb") as w:
        assert w.getsampwidth() == 2 and w.getframerate() == SR, path
        ch = w.getnchannels()
        raw = w.readframes(w.getnframes())
    vals = struct.unpack("<%dh" % (len(raw) // 2), raw)
    return [sum(vals[i:i + ch]) / (ch * 32768.0) for i in range(0, len(vals), ch)]


# ----------------------------------------------------------------------------- the sounds
def porch_forest_night():
    """20 s seamless loop. Every modulation completes a whole number of cycles in L, the noise
    is filtered as a CIRCULAR buffer (run twice, keep the second pass), creaks sit clear of the
    seam."""
    rng = random.Random(24091)
    L = 20.0
    n = int(SR * L)
    white = [rng.uniform(-1, 1) for _ in range(n)]
    # brown-ish body: lowpass twice, circularly
    body = lowpass(lowpass(white + white, 380), 380)[n:]
    # the hiss of needles: a band that breathes
    hiss_src = highpass(white + white, 1600)[n:]
    hiss = sweep_bp(hiss_src + hiss_src,
                    lambda t: 2600 + 900 * math.sin(TAU * 3 * (t % L) / L), 0.9)[n:]
    out = [0.0] * n
    for i in range(n):
        t = i / SR
        swell = 0.55 + 0.3 * math.sin(TAU * 2 * t / L) + 0.15 * math.sin(TAU * 5 * t / L + 1.3)
        gust = max(0.0, math.sin(TAU * 3 * t / L + 0.4)) ** 3
        out[i] = body[i] * 3.0 * swell + hiss[i] * (0.18 + 0.5 * gust)
    # two low creaks of a trunk / the porch boards, well away from the seam
    for tc, f_rate, fc in ((6.3, 34.0, 520.0), (14.1, 27.0, 430.0)):
        crk = buf(1.1)
        ph = 0.0
        for i in range(len(crk)):
            t = i / SR
            rate = f_rate * (1 + 0.25 * math.sin(TAU * 1.3 * t)) + rng.uniform(-3, 3)
            ph += rate / SR
            if ph >= 1.0:
                ph -= 1.0
                crk[i] = rng.uniform(0.6, 1.0)
        crk = sweep_bp(crk, lambda t, fc=fc: fc * (1 + 0.15 * t), 6.0)
        e = [math.sin(math.pi * min(1.0, i / len(crk))) ** 2 for i in range(len(crk))]
        crk = [a * b * 0.9 for a, b in zip(crk, e)]
        add(out, tc, lambda t, c=crk: c[min(len(c) - 1, int(t * SR))], 1.1)
    write("porch_forest_night.wav", out, -12.0)


def window_burst():
    rng = random.Random(24092)
    out = buf(2.0)
    # impact: a thump and a broadband crack
    add(out, 0.0, lambda t: 0.9 * env_ad(t, 0.002, 0.05) * math.sin(TAU * (70 + 90 * math.exp(-t * 40)) * t), 0.3)
    crack = [rng.uniform(-1, 1) * env_ad(i / SR, 0.0005, 0.09) for i in range(int(SR * 0.5))]
    crack = highpass(crack, 900)
    add(out, 0.0, lambda t: 1.3 * crack[min(len(crack) - 1, int(t * SR))], 0.5)
    if os.path.exists(GLASS):
        g = read_wav(GLASS)
        add(out, 0.01, lambda t: 0.8 * g[min(len(g) - 1, int(t * SR))], len(g) / SR)
    # the shard rain: many short inharmonic tinkles, dense at first, thinning out
    t0 = 0.02
    while t0 < 1.85:
        f = rng.uniform(2800, 9500)
        a = rng.uniform(0.15, 0.55) * (1.0 - 0.45 * t0 / 1.85)
        d = rng.uniform(0.015, 0.07)

        def tink(t, f=f, a=a, d=d):
            e = env_ad(t, 0.0008, d)
            return a * e * (math.sin(TAU * f * t) + 0.5 * math.sin(TAU * f * 1.51 * t) + 0.3 * math.sin(TAU * f * 2.37 * t))
        add(out, t0, tink, 6 * d)
        t0 += rng.uniform(0.002, 0.012) + 0.05 * (t0 / 1.85) ** 2
    out = saturate(out, 1.6)
    fade(out, 0.0, 0.15)
    write("window_burst.wav", out, -3.0)


def porch_wind_gust():
    rng = random.Random(24093)
    T = 4.0
    n = int(SR * T)
    white = [rng.uniform(-1, 1) for _ in range(n)]

    def shape(t):          # swell 1.4 s up, 2.6 s away
        return (t / 1.4) ** 1.5 if t < 1.4 else math.exp(-(t - 1.4) / 0.9)

    rush = sweep_bp(white, lambda t: 350 + 900 * shape(t), 0.8)
    whistle_n = sweep_bp(white, lambda t: 780 + 520 * shape(t) + 60 * math.sin(TAU * 2.2 * t), 18.0)
    out = [0.0] * n
    ph = 0.0
    for i in range(n):
        t = i / SR
        s = shape(t)
        f = 820 + 480 * s + 25 * math.sin(TAU * 3.1 * t)
        ph += TAU * f / SR
        out[i] = s * (rush[i] * 1.2 + whistle_n[i] * 2.5) + 0.05 * s * s * math.sin(ph)
    fade(out, 0.05, 0.3)
    write("porch_wind_gust.wav", out, -6.0)


def guillotine_rope():
    rng = random.Random(24094)
    out = buf(1.05)
    # stick-slip squeak: an irregular pulse train through two pulley resonances
    n = int(SR * 0.8)
    pulses = [0.0] * n
    ph = 0.0
    for i in range(n):
        t = i / SR
        rate = 70 + 60 * math.sin(math.pi * t / 0.8) + rng.uniform(-8, 8)
        ph += rate / SR
        if ph >= 1.0:
            ph -= 1.0
            pulses[i] = rng.uniform(0.5, 1.0)
    sq = [a + 0.6 * b for a, b in zip(sweep_bp(pulses, lambda t: 820 + 250 * t, 12.0),
                                      sweep_bp(pulses, lambda t: 1650 + 400 * t, 14.0))]
    rope = lowpass([rng.uniform(-1, 1) for _ in range(n)], 900)
    for i in range(n):
        e = math.sin(math.pi * i / n) ** 0.7
        sq[i] = (sq[i] * 1.6 + rope[i] * 0.4) * e
    add(out, 0.0, lambda t: sq[min(n - 1, int(t * SR))], 0.8)

    # the catch: a metal clack
    def clack(t):
        e = env_ad(t, 0.0005, 0.045)
        return e * (math.sin(TAU * 1230 * t) + 0.7 * math.sin(TAU * 2890 * t) + 0.45 * math.sin(TAU * 4310 * t)) \
            + 0.8 * env_ad(t, 0.0003, 0.006) * rng.uniform(-1, 1)
    add(out, 0.84, clack, 0.2)
    write("guillotine_rope.wav", out, -3.0)


def guillotine_drop():
    rng = random.Random(24095)
    out = buf(1.5)
    # the blade scraping down its grooves: a band of noise rising, and a screech on top
    n = int(SR * 0.58)
    scr = sweep_bp([rng.uniform(-1, 1) for _ in range(n)], lambda t: 600 + 4200 * (t / 0.58) ** 1.6, 4.0)
    ph = 0.0
    for i in range(n):
        t = i / SR
        f = 700 + 2600 * (t / 0.58) ** 1.4 + 40 * math.sin(TAU * 31 * t)
        ph += TAU * f / SR
        e = min(1.0, t / 0.05) * (0.5 + 0.5 * t / 0.58)
        scr[i] = e * (scr[i] * 1.8 + 0.22 * math.sin(ph) + 0.1 * math.sin(2.02 * ph))
    add(out, 0.0, lambda t: scr[min(n - 1, int(t * SR))], 0.58)
    tk = 0.6
    # the heavy low thunk into the block
    add(out, tk, lambda t: 1.4 * env_ad(t, 0.002, 0.16) * math.sin(TAU * (48 + 110 * math.exp(-t * 25)) * t), 0.8)
    knock = lowpass([rng.uniform(-1, 1) * env_ad(i / SR, 0.0005, 0.03) for i in range(int(SR * 0.2))], 700)
    add(out, tk, lambda t: 2.5 * knock[min(len(knock) - 1, int(t * SR))], 0.2)
    # and the blade ringing after it
    add(out, tk, lambda t: 0.25 * env_ad(t, 0.001, 0.35) * (math.sin(TAU * 310 * t) + 0.6 * math.sin(TAU * 787 * t) + 0.35 * math.sin(TAU * 1523 * t)), 0.9)
    out = saturate(out, 1.4)
    fade(out, 0.005, 0.1)
    write("guillotine_drop.wav", out, -3.0)


def melon_burst():
    rng = random.Random(24096)
    out = buf(1.5)
    # the rind cracking: a hard click and a hollow low knock
    add(out, 0.0, lambda t: 1.0 * env_ad(t, 0.0003, 0.004) * rng.uniform(-1, 1), 0.03)
    add(out, 0.0, lambda t: 0.9 * env_ad(t, 0.002, 0.05) * math.sin(TAU * (95 + 60 * math.exp(-t * 50)) * t), 0.3)
    # the wet body giving way: lowpassed noise swelling out
    n = int(SR * 0.45)
    body = lowpass(lowpass([rng.uniform(-1, 1) for _ in range(n)], 900), 900)
    add(out, 0.01, lambda t: 3.5 * env_ad(t, 0.01, 0.12) * body[min(n - 1, int(t * SR))], 0.45)
    # splatter: many small wet drops landing, each a short resonant squelch
    t0 = 0.03
    while t0 < 1.2:
        fc = rng.uniform(280, 1600)
        a = rng.uniform(0.2, 0.7) * (1.0 - 0.6 * t0 / 1.2)
        d = rng.uniform(0.006, 0.03)
        m = int(SR * d * 5)
        drop = sweep_bp([rng.uniform(-1, 1) * env_ad(i / SR, 0.001, d) for i in range(m)],
                        lambda t, fc=fc: fc * (1 - 2.5 * t), 3.0)
        add(out, t0, lambda t, dr=drop, a=a: a * 3 * dr[min(len(dr) - 1, int(t * SR))], m / SR)
        t0 += rng.uniform(0.004, 0.03) + 0.08 * (t0 / 1.2) ** 2
    pk = max(abs(x) for x in out)
    out = saturate([x / pk for x in out], 2.5)      # a sting: density, not just a peak
    fade(out, 0.0, 0.1)
    write("melon_burst.wav", out, -3.0)


def ghost_woman_scream():
    rng = random.Random(24097)
    T = 2.5

    def f0(t):
        base = 620 + 380 * min(1.0, t / 0.35) - 120 * max(0.0, t - 1.6)
        return base * (1 + 0.035 * math.sin(TAU * 6.3 * t) + 0.01 * math.sin(TAU * 13.7 * t))

    def forms(t):
        k = min(1.0, t / 0.5)          # "aah" opening into "eeh"
        return [(850, 180, 1.0), (1250 + 1100 * k, 220, 0.8), (2950, 300, 0.55), (3700, 400, 0.35), (5200, 900, 0.2)]

    def amp(t):
        return min(1.0, t / 0.07) * (1.0 if t < 1.9 else math.exp(-(t - 1.9) / 0.22))

    v = voice(T, f0, forms, amp, max_hz=10000, jitter=0.02, rng=rng)
    # a raw breath edge riding the voice
    br = highpass([rng.uniform(-1, 1) for _ in range(len(v))], 2500)
    v = [a + 0.18 * b * amp(i / SR) for i, (a, b) in enumerate(zip(v, br))]
    pk = max(abs(x) for x in v)
    v = saturate([x / pk for x in v], 2.8)
    v = comb_reverb(v, 0.18, 1.1, 0.0)
    fade(v, 0.0, 0.08)
    write("ghost_woman_scream.wav", v, -3.0)


def ghost_crawler_screech():
    rng = random.Random(24098)
    T = 2.0
    n = int(SR * T)
    out = [0.0] * n
    # the guttural bed: a rough low voice with a sub-octave
    growl = voice(T, lambda t: 88 + 14 * math.sin(TAU * 0.9 * t),
                  lambda t: [(480, 160, 1.0), (880, 200, 0.7), (2400, 500, 0.25)],
                  lambda t: min(1.0, t / 0.08) * (0.55 + 0.45 * abs(math.sin(TAU * 14 * t))) * (1.0 if t < 1.7 else math.exp(-(t - 1.7) / 0.1)),
                  max_hz=4000, jitter=0.05, rng=rng)
    # the screech: a harsh high voice in the middle
    scr = voice(T, lambda t: 1250 + 300 * math.sin(math.pi * min(1.0, max(0.0, (t - 0.55) / 1.0))) + 40 * math.sin(TAU * 23 * t),
                lambda t: [(1500, 250, 1.0), (2900, 350, 0.8), (4300, 500, 0.5)],
                lambda t: 0.0 if t < 0.55 or t > 1.6 else math.sin(math.pi * (t - 0.55) / 1.05) ** 0.6,
                max_hz=9000, jitter=0.04, rng=rng)
    for i in range(n):
        out[i] = growl[i] * 1.0 + scr[i] * 0.9
    pk = max(abs(x) for x in out)
    out = saturate([x / pk for x in out], 3.0)
    # the clicking: an irregular train of hard resonant clicks throughout
    t0 = 0.02
    while t0 < 1.85:
        fc = rng.uniform(1800, 3200)
        a = rng.uniform(0.5, 1.0)
        m = int(SR * 0.012)
        clk = sweep_bp([rng.uniform(-1, 1) * env_ad(i / SR, 0.0002, 0.0015) for i in range(m)], lambda t, fc=fc: fc, 5.0)
        add(out, t0, lambda t, c=clk, a=a: a * 4 * c[min(len(c) - 1, int(t * SR))], m / SR)
        t0 += rng.uniform(0.025, 0.07) if rng.random() > 0.2 else rng.uniform(0.1, 0.18)
    fade(out, 0.0, 0.06)
    write("ghost_crawler_screech.wav", out, -3.0)


def ghost_tall_howl():
    rng = random.Random(24099)
    T = 4.0

    def f0(t):
        rise = 52 + 26 * math.sin(math.pi * min(1.0, t / 2.8)) ** 1.5
        return rise * (1 + 0.02 * math.sin(TAU * 3.1 * t))

    forms = lambda t: [(290, 120, 1.0), (680, 160, 0.6), (2300, 400, 0.12)]
    amp = lambda t: min(1.0, t / 0.6) * (1.0 if t < 2.2 else math.exp(-(t - 2.2) / 0.6))
    a = voice(T, f0, forms, amp, max_hz=3500, jitter=0.01, rng=rng)
    b = voice(T, lambda t: f0(t) * 1.012, forms, amp, max_hz=3500, jitter=0.01, rng=rng)
    sub = [0.0] * len(a)
    ph = 0.0
    for i in range(len(sub)):
        t = i / SR
        ph += TAU * 0.5 * f0(t) / SR
        sub[i] = 0.5 * amp(t) * math.sin(ph)
    breath = lowpass([rng.uniform(-1, 1) for _ in range(len(a))], 600)
    out = [x + y + z + 0.6 * w * amp(i / SR) for i, (x, y, z, w) in enumerate(zip(a, b, sub, breath))]
    pk = max(abs(x) for x in out)
    out = saturate([x / pk for x in out], 1.5)
    out = comb_reverb(out, 0.35, 2.4, 0.0)
    fade(out, 0.0, 0.5)
    write("ghost_tall_howl.wav", out, -4.0)


def forest_run_leaves():
    rng = random.Random(24100)
    out = buf(2.0)
    t0 = 0.03
    while t0 < 1.8:
        a = rng.uniform(0.7, 1.0)
        # the thud of the foot
        thud = lowpass([rng.uniform(-1, 1) * env_ad(i / SR, 0.003, 0.03) for i in range(int(SR * 0.12))], 180)
        add(out, t0, lambda t, th=thud, a=a: 6 * a * th[min(len(th) - 1, int(t * SR))], 0.12)
        # the crunch: a cloud of tiny dry crackles
        for _ in range(rng.randint(22, 40)):
            tc = t0 + abs(rng.gauss(0.0, 0.03))
            fc = rng.uniform(2000, 6500)
            m = int(SR * 0.006)
            cr = sweep_bp([rng.uniform(-1, 1) * env_ad(i / SR, 0.0002, 0.0012) for i in range(m)], lambda t, fc=fc: fc, 2.0)
            k = a * rng.uniform(0.6, 1.4) * 1.2
            add(out, tc, lambda t, c=cr, k=k: k * c[min(len(c) - 1, int(t * SR))], m / SR)
        t0 += rng.uniform(0.2, 0.26)
    fade(out, 0.0, 0.08)
    write("forest_run_leaves.wav", out, -5.0)


def witch_hum():
    rng = random.Random(24101)
    T = 5.0
    # a slow minor figure, humming through closed lips: A3 C4 B3 A3 G#3 A3
    notes = [(0.0, 220.0), (0.9, 261.6), (1.7, 246.9), (2.5, 220.0), (3.3, 207.7), (4.0, 220.0)]

    def f0(t):
        f = notes[0][1]
        for i, (ts, fn) in enumerate(notes):
            if t >= ts:
                prev = notes[i - 1][1] if i else fn
                g = min(1.0, (t - ts) / 0.18)          # old voices slide into notes
                f = prev + (fn - prev) * g
        wob = 1 + (0.012 + 0.008 * math.sin(TAU * 0.37 * t)) * math.sin(TAU * 4.6 * t) + 0.004 * math.sin(TAU * 1.3 * t)
        return f * wob

    # "mmm" through an old throat: a strong nasal low formant plus enough buzz above it that
    # it reads as a VOICE rather than a sine (measured: the first cut put 98 % below 300 Hz)
    forms = lambda t: [(250, 120, 1.0), (520, 200, 0.45), (1100, 300, 0.3), (2500, 500, 0.12)]
    amp = lambda t: min(1.0, t / 0.4) * (1.0 if t < 4.4 else max(0.0, 1 - (t - 4.4) / 0.6)) * (0.8 + 0.2 * math.sin(TAU * 0.9 * t))
    a = voice(T, f0, forms, amp, max_hz=3000, jitter=0.01, rng=rng)
    b = voice(T, lambda t: f0(t) * 1.0035, forms, amp, max_hz=3000, jitter=0.01, rng=rng)
    breath = lowpass(highpass([rng.uniform(-1, 1) for _ in range(len(a))], 300), 1500)
    out = [x + 0.8 * y + 0.35 * z * amp(i / SR) for i, (x, y, z) in enumerate(zip(a, b, breath))]
    out = comb_reverb(out, 0.15, 0.8, 0.0)
    fade(out, 0.05, 0.3)
    write("witch_hum.wav", out, -10.0)


SOUNDS = [porch_forest_night, window_burst, porch_wind_gust, guillotine_rope, guillotine_drop,
          melon_burst, ghost_woman_scream, ghost_crawler_screech, ghost_tall_howl,
          forest_run_leaves, witch_hum]


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for fn in SOUNDS:
        fn()


if __name__ == "__main__":
    main()
